name: Send Workflow Logs to Splunk

# Controls when the action will run.
on:
  workflow_dispatch: # manual trigger
  workflow_run:
    workflows: ["*"]
    types:
      - completed

env:
  triggerID: ${{ github.run_id }}
  triggerJob: ${{ github.event.workflow }}

jobs:
  WriteLogs:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.name!='WriteLogs'}}

    steps:
    
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Output Job ID
        run: echo ${{ github.run_id }}

      - name: Send Workflow logs to Splunk
        if: ${{ always() }}
        uses: ./.github/actions/log_to_splunk
        with:
          splunk-url: ${{ secrets.HEC_URL }}
          hec-token: ${{ secrets.HEC_TOKEN }}
          github-token: ${{ secrets.GH_PAT }}
          workflowID: ${{ env.triggerID }}
          source: ${{ env.triggerJob }}